- name: Copy SSH Key to Nodes
  hosts: all
  tasks:
    - name: Ensure SSH key is present on all nodes
      authorized_key:
        user: ubuntu
        state: present
        key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
